os:
  - osx
  - linux
language: node_js
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
branches:
  only:
    - master
    - /release\/.*/

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_token: "$NPM_TOKEN"
  on:
    branch: master
