os:
  - osx
  - linux
language: node_js
node_js:
  - '14'
  - '15'
  - '16'
branches:
  only:
    - master
    - /tags\/.*/

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_token: "$NPM_TOKEN"
  on:
    tags: true
